name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Debug _site directory
      run: |
        echo "Contents of _site directory:"
        ls -la _site

    - name: Setup Pages
      uses: actions/configure-pages@v5
      with:
        # Ensure GitHub Pages is enabled
        enablement: 'always'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Path to the directory containing the built site
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
